[pyprland]
plugins = [
    "scratchpads"
]

[scratchpads.terminal]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50

[scratchpads.volume]
animation = "fromRight"
command = "pwvucontrol"
class = "com.saivert.pwvucontrol-pypr"
size = "40% 90%"
unfocus = "hide"

[scratchpads.network]
animation = "fromRight"
command = "nm-connection-editor"
class = "nm-connection-editor-pypr"
size = "40% 90%"
unfocus = "hide"
